apiVersion: v1
kind: Service
metadata:
  name: weather-dashboard-service
spec:
  type: LoadBalancer
  selector:
    app: weather-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
